server:
  port: 882
  servlet:
    context-path: /
spring:
  mvc:
    view:
      suffix: .html
      prefix: /views/
    static-path-pattern: /**
  resources:
    static-locations: classpath:/templates/,classpath:/static/